### ISSUE TITLE
globbing doesn't seem to allow file exclusion

### ISSUE THREAD

**Issue by Carnid** [sindresorhus/gulp-ruby-sass#295] opened 2016-10-25 16:08 UTC
It is my understanding that the file matching pattern **should** be the same for `gulp-ruby-sass` and `gulp.src()`, however...

```
gulpRubySass([
    'source/sass/**/*.scss',
    '!source/sass/exclude-me.scss'
], {
    loadPath: ['source/sass']
}).on('error', gulpRubySass.logError)
.pipe(gulp.dest(`build/css`));
```
still parses `exclude-me.scss`.

If I run the same glob pattern in `gulp.src()`, 
```
gulp.src([
    'source/sass/**/*.scss',
    '!source/sass/exclude-me.scss'
]).pipe(gulp.dest(`source/sass/temp/'));
```
it is not included, as expected.

**Comment by kevva** [comment] 2016-10-26 18:58
Duplicate of https://github.com/sindresorhus/gulp-ruby-sass/issues/269.

**Closed by kevva** 2016-10-26 18:58 UTC
