### ISSUE TITLE
On error function not working

### ISSUE THREAD

**Issue by entozoon** [sindresorhus/gulp-ruby-sass#208] opened 2015-03-09 16:50 UTC
on (error) doesn't work, or at least not how it used to.. for example:
```
gulp.task('sass', function() {
	return sass('./scss/site.scss')
	.on('error', function (err) {
		console.error("Hello?");
	})
	.pipe(gulp.dest('./css'));
});
```

If there is an error in the sass file, say a missing $variable, the undefined variable is output to the console via gulp-ruby-sass stderr.. however the given on('error') function seemingly does nothing.

Interestingly if I change it to 
```
return sass('./scss')
```

The error function is used, but of course that's not what I want - it ought to only compile site.scss

**Comment by kevva** [comment] 2015-03-09 18:16
Globbing and setting specific files as source doesn't work yet. There's an open PR for this here https://github.com/sindresorhus/gulp-ruby-sass/pull/137.

**Comment by robwierzbowski** [comment] 2015-03-20 18:16
I think the main issue here has been edited, and it's hard to figure out what the original problem is and how to reproduce. I'm going to close this issue as a duplicate of https://github.com/sindresorhus/gulp-ruby-sass/issues/164 (where there is similar issues and fixes being discussed). Feel free to post your task and what you expect it to do there.

**Closed** 2015-03-20 18:16 UTC
