### ISSUE TITLE
Needless argument for stderr.

### ISSUE THREAD

**Issue by bartgarbiak** [sindresorhus/gulp-ruby-sass#145] opened 2014-10-13 11:32 UTC
The module shows following warning, then exits the task.
```gulp-ruby-sass: stderr: OptionParser::NeedlessArgument: needless argument: --update=:
  Use --trace for backtrace```

I assume the cause is that the path given to the compiler is not relative, and not wrapped in quotations marks either. This is the command used to run gulp-ruby-sass:
```gulp-ruby-sass: Running command: sass --style=expanded --update=C:/Users/Admin/AppData/Local/Temp/gulp-ruby-sass:C:/Users/Admin/AppData/Local/Temp/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01
ce9 --load-path=themes/site_themes/default_site/styles.group/sass```

I'm using Windows 8.1, Ruby193, SASS 3.4.5. On another machine (same setup, but Windows 7) everything works correctly.

**Comment by sirMackk** [comment] 2015-01-04 01:58
Same thing here - using node v0.10.13, ubuntu box, tried both sass 3.3.0 and 3.4.9. Getting this output: 

    [20:52:47] gulp-ruby-sass: Running command: sass --update=/tmp/gulp-ruby-sass:/tmp/gulp-ruby-sass/_14139e58-9ebe-4c0f-beca-73a65bb01ce9 --load-path=assets/sass
    [20:52:48] gulp-ruby-sass: stderr: OptionParser::NeedlessArgument: needless argument: --update=:

Tried @bartgarbiak 's method, no luck with it here.

**Comment by robwierzbowski** [comment] 2015-01-16 19:00
Ok, figured this one out I think. Fix incoming, will ping.

**Comment by robwierzbowski** [comment] 2015-01-16 19:08
It looks like this should be impossible with 1.0.0-alpha. The issue is (just like it says :smile:) that update is an argumentless flag, and the directory mappings are a separate argument entirely. This used to be allowed in older versions of Sass, but isn't anymore.

In the 1.0.0-alpha release we have code here https://github.com/sindresorhus/gulp-ruby-sass/blob/1.0.0-alpha/index.js#L62-L63 that only sets `--update` to true, and adds the directory mappings as a separate argument. Marking this as fixed; thanks everyone for the good reporting.

**Closed by robwierzbowski** 2015-01-16 19:08 UTC
Labels: bug from pre 1.0

**Comment by tams** [comment] 2015-10-20 12:34
For the folks still getting the error after trying everything else in this thread: in our case the cause was a Sass version mismatch: worked on 3.4.18, but failed on 3.3.14.

A Sass gem update (``$ sudo gem update sass``) solved the error.

**Comment by robwierzbowski** [comment] 2015-10-20 15:13
Thanks for the update :+1:
