### ISSUE TITLE
Issues with error handling and events / use with Plumber

### ISSUE THREAD

**Issue by alexmccabe** [sindresorhus/gulp-ruby-sass#164] opened 2014-12-03 10:39 UTC
I am having trouble understanding how this new version can be used with gulp-plumber. 

Gulp task:

    return plugins.rubySass(paths.sass.input, {
        sourcemap: sourceMap
    })
    .pipe(plugins.plumber({
        errorHandler: notify.onError("Error: <%= error.message %>")
    }));

I get an error in the console when I force a SCSS error.

    gulp-ruby-sass stdout: directory

    events.js:72
        throw er; // Unhandled 'error' event
              ^
     Error: error public/installations/src/sass/components/_buttons.scss (Line 47: Invalid CSS after "...g: .68em 1.5em}": expected "}", was "")

So the error isn't being picked up by plumber.

**Comment by adammockor** [comment] 2015-01-13 17:21
But, standard error handling probably doesn't work to. I got task like below and when I force error in scss source file, error are emitted from rubySass and not from error event.

```javascript
gulp.task('styles', function () {
  return rubySass('app/styles/main.scss', {
      sourcemap: false,
      style: 'expanded',
      lineNumbers: true
    })
    .on('error', function (err) { 
      console.log('Hey error!  + 'err); 
    })
    .pipe(sourcemaps.write())
    .pipe(autoprefixer({browsers: ['last 2 version']}))
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream:true}));
});
```
Version of gulp-ruby-sass is "^1.0.0-alpha" and sass "3.4.9".

**Comment by ryanjbonnell** [comment] 2015-01-29 20:48
I'm experiencing the same type of error-handling issue, except I'm trying to use [Gulp Notify][1].

Consider the following example, adapted from Adam Močkoř (**adammockor**):

```javascript
gulp.task('styles', function () {
  return rubySass('scss/bootstrap.scss', {
      sourcemap: false,
      style: 'expanded',
      lineNumbers: true
    })
    .on('error', function (err) {
      console.log('Hey error! ' + err);
    })
    .pipe(gulp.dest('css'))
});
```

When I force an error in my Sass file, the custom error message text never gets output to the console.

Instead, what gets output is:

```console
$ gulp styles
[12:27:32] Using gulpfile ~/Sites/example.dev/gulpfile.js
[12:27:32] Starting 'styles'...
[12:27:32] gulp-ruby-sass stderr: Error: Invalid CSS after "width: 20px": expected "{", was ";"
        on line 11 of scss/bootstrap.scss
  Use --trace for backtrace.
[12:27:32] Finished 'styles' after 385 ms
```
Nowhere in the console output does the text "Hey error!" appear.

I'm using Gulp Ruby Sass v1.0.0-alpha and Sass v3.4.10 on Mac OS X 10.10.2 "Yosemite".

[1]: https://www.npmjs.com/package/gulp-notify

**Comment by philipb3** [comment] 2015-02-06 19:08
I've been having success using gulp-notify and the standard error handling instead of gulp-plumber:

    gulp.task('styles', function() {

        return sass(src + '/scss', {
            noCache: true,
            sourcemap: true,
            style: 'compressed'
        })
        .on('error', function(err) {
            notify.onError({
                title: 'Error!',
                message: '<%= error.message %>',
                sound: 'Beep'
            })(err);
            this.emit('end');
        })
    });

**Comment by fricks** [comment] 2015-02-13 10:33
@philipb3 I don't have success with gulp-notify yet and it's a pain :/

**Comment by russellf9** [comment] 2015-02-21 16:55
I was having an issue too, I can confirm the the snippet from [philipb3](https://github.com/philipb3) works!

Very handy when my watch task is running.

**Comment by SamHH** [comment] 2015-02-26 14:29
Same here. @philipb3's snippet works perfectly on my end.

**Comment by adammockor** [comment] 2015-03-02 13:14
@philipb3 @fricks no luck for me either. (alpha.3)

**Comment by amercier** [comment] 2015-03-05 00:37
Same problem here (Sass 3.4.13,  gulp-ruby-sass 1.0.0-alpha3). @philipb3 's snippet doesn't work for me. Sass syntax errors are still not emitting 'error' events.

Instead of [index.js#L137-L146](https://github.com/sindresorhus/gulp-ruby-sass/blob/rw/1.0/index.js#L137-L146), shouldn't it be the following?

```
	sass.stderr.on('data', function (data) {
		var msg = formatMsg(data, destDir);

		if (!matchNoSass.test(msg)) {
			gutil.log('gulp-ruby-sass stderr:', msg);
		}
		else {
			stream.emit('error', newErr(msg));
		}
	});
```

This way, it emits an error when sass outputs on stderr.

**Comment by robwierzbowski** [comment] 2015-03-20 18:03
The purpose of that order is twofold: 

1. We don't want to to emit an error when sass outputs on stderr. The comment above notes that Sass puts warnings and debug statements on stderr, which aren't actually errors. We just want to log them.

2. Spawn outputs no Sass executable errors on both stderr and error, and we emit the error on('error') a couple lines below.

**Comment by robwierzbowski** [comment] 2015-03-20 18:04
The error handling in here is really a pain in the butt. I think I might pull it out into its own file to make it a little more understandable (or at least confined to one space).

**Comment by robwierzbowski** [comment] 2015-03-20 18:09
@ryanjbonnell I used a task like:

```js
// inline sourcemaps
gulp.task('sass-inline', function() {
	return sass('source', { sourcemap: true })
	.on('error', function (err) {
	  console.error('Hey Error!', err.message);
   })
	.pipe(sourcemaps.write())
	.pipe(gulp.dest('result'));
});
```

When running it with syntax erroring Sass I get:

```shell
⚡ Contrib/gulp-ruby-sass/fixture (rw/1.0 ⚒)
➜ gulp sass-inline
[gulp] Using gulpfile ~/Documents/Contrib/gulp-ruby-sass/fixture/gulpfile.js
[gulp] Starting 'sass-inline'...
[14:07:14] gulp-ruby-sass stdout: directory
[14:07:14] gulp-ruby-sass stderr: source/fixture-a.scss:11 DEBUG: This is a debug statement
WARNING: This is a warn statement
         on line 12 of source/fixture-a.scss
[14:07:14] gulp-ruby-sass stdout: write fixture-a.css
      write fixture-a.css.map
Hey Error! error source/fixture-error.scss (Line 1: File to import not found or unreadable: i-dont-exist.
Load path: /Users/robw/Documents/Contrib/gulp-ruby-sass/fixture/source)
[14:07:14] gulp-ruby-sass stdout: directory nested
[14:07:14] gulp-ruby-sass stdout: write nested/fixture-b.css
      write nested/fixture-b.css.map
[gulp] Finished 'sass-inline' after 332 ms
```

I'm getting the `Hey Error!` text logged to the console. Is there any difference between the way we're using the plugin?

**Comment by robwierzbowski** [comment] 2015-03-20 18:12
As far as I can tell the error handling is working as I'd expect it to in the current codebase. But I'm sure it could be improved. How would everyone in this issue expect grs errors to work? Like Sass, printed to the console? How about bundler and gem missing errors?

**Comment by adammockor** [comment] 2015-03-21 09:19
This is still super weird to me, version 1.0.1.

When I run tests and `gulp sass-inline` inside this repository, I got output as expected with custom error message from .on('error').

But this still do not work: (I got error in browser and console, but not customized from .on('error'))

```
gulp.task('styles', function () {
  return rubySass(config.styles.src, {
      sourcemap: true,
      style: 'expanded',
      lineNumbers: true
    })
    .on('error', function (err) {
      console.error('Hey! Error!', err.message);
    })
    .pipe(postcss([
      autoprefixer(config.styles.autoprefixerCfg)
    ]))
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(config.styles.dest))
    .pipe(reload({stream:true}));
});
```

**Comment by robwierzbowski** [comment] 2015-03-21 13:55
Huh, that is bizarre. Maybe delete your gulp and gulp ruby sass modules and
re-install? Upgrade node/iojs just in case?

On Saturday, March 21, 2015, Adam Močkoř <notifications@github.com> wrote:

> This is still super weird to me, version 1.0.1.
>
> When I run tests and gulp sass-inline inside this repository, I got
> output as expected with custom error message from .on('error').
>
> But this still do not work: (I got error in browser and console, but not
> customized from .on('error'))
>
> gulp.task('styles', function () {
>   return rubySass(config.styles.src, {
>       sourcemap: true,
>       style: 'expanded',
>       lineNumbers: true
>     })
>     .on('error', function (err) {
>       console.error('Hey! Error!', err.message);
>     })
>     .pipe(postcss([
>       autoprefixer(config.styles.autoprefixerCfg)
>     ]))
>     .pipe(sourcemaps.write())
>     .pipe(gulp.dest(config.styles.dest))
>     .pipe(reload({stream:true}));
> });
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/164#issuecomment-84286136>
> .
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by adammockor** [comment] 2015-03-21 19:09
I tried that. Look at my edit, that's the cause. It has to do something with globbing.

**Comment by robwierzbowski** [comment] 2015-03-21 20:01
That's odd. A single file should still work. I'll do some testing, thanks for the extra info.

**Comment by robwierzbowski** [comment] 2015-03-23 19:48
Looks like @adammockor found the reason for this and PR'd a solution. I'll work on getting that in ASAP.

**Comment by robwierzbowski** [comment] 2015-04-26 15:43
Sass throws single file missing errors to stderr and directory missing errors to stdout :P. https://github.com/sindresorhus/gulp-ruby-sass/pull/221 fixes so g-r-s throws both errors.

This issue asks about plumber, and also asking about the file vs dir error handling. Since the file vs dir error handling is fixed in https://github.com/sindresorhus/gulp-ruby-sass/pull/221, and the README documents that you can't use a source adapter with plumber (yet), I'm going to close witht the merge of the PR. Please open a new issue for any future problems.

**Closed** 2015-04-26 15:44 UTC
