### ISSUE TITLE
on error not working

### ISSUE THREAD

**Issue by newyorktime** [sindresorhus/gulp-ruby-sass#227] opened 2015-05-24 03:26 UTC
Hi!
I follow the instructions but I don't get it working.
```
	sass('./src/sass/main.sass', {style: 'expanded'})
		.on('error', notify.onError({
			title: "SASS COMPILER",
			message: "Error en: <%= error.message %>"
		}))
		.pipe(gulp.dest('./dist/assets/css'))
		.pipe(rename('main.min.css'))
		.pipe(minifyCSS())
		.pipe(gulp.dest('./dist/assets/css'))
		.pipe(livereload());
```

**Comment by robwierzbowski** [comment] 2015-05-24 17:21
Can you tell me what you were expecting and what happened instead?

On Saturday, May 23, 2015, newyorktime <notifications@github.com> wrote:

> Hi!
> I follow the instructions but I don't get it working.
>
>     sass('./src/sass/main.sass', {style: 'expanded'})
>         .on('error', notify.onError({
>             title: "SASS COMPILER",
>             message: "Error en: <%= error.message %>"
>         }))
>         .pipe(gulp.dest('./dist/assets/css'))
>         .pipe(rename('main.min.css'))
>         .pipe(minifyCSS())
>         .pipe(gulp.dest('./dist/assets/css'))
>         .pipe(livereload());
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sindresorhus/gulp-ruby-sass/issues/227>.
>


-- 
Rob Wierzbowski
@robwierzbowski <http://twitter.com/#!/robwierzbowski>
http://github.com/robwierzbowski
http://robwierzbowski.com

**Comment by sirlancelot** [comment] 2015-05-27 18:55
If Sass encounters a compilation error, it seems to still get sent to stdout instead of stderr. I'm on Windows and am having the same issue.

**Comment by exequiel09** [comment] 2015-06-07 01:20
I'm on OSX and this happens to me also.

**Comment by tupton** [comment] 2015-06-09 19:34
This also happens to me on OS X 10.10.3.

```
❯ l
total 24
drwxr-xr-x  6 tupton  staff   204B Jun  9 14:32 ./
drwxr-xr-x  9 tupton  staff   306B Jun  9 14:29 ../
-rw-r--r--  1 tupton  staff   255B Jun  9 14:31 Gulpfile.js
drwxr-xr-x  5 tupton  staff   170B Jun  9 14:30 node_modules/
-rw-r--r--  1 tupton  staff   2.6K Jun  9 14:32 test.css
-rw-r--r--  1 tupton  staff    46B Jun  9 14:31 test.scss
❯ cat Gulpfile.js
var gulp = require('gulp'),
    sass = require('gulp-ruby-sass');

gulp.task('sass', function() {
    return sass('test.scss')
        .on('error', function(error) {
            console.error('oh no', error);
        })
        .pipe(gulp.dest('.'));
});
❯ gulp sass
[14:33:43] Using gulpfile ~/code/tmp/gulp-ruby-sass/Gulpfile.js
[14:33:43] Starting 'sass'...
[14:33:43] Error: Invalid CSS after "...ackground-color": expected ";", was ": #000;"
        on line 3 of test.scss
  Use --trace for backtrace.
[14:33:43] Finished 'sass' after 187 ms
```

**Comment by tupton** [comment] 2015-06-09 19:39
Oh, I think I see. It seems that this plugin only emits the error event if there are problems with it specifically (can't find the sass executable, can't find the file to run sass on, etc.), not when there are actual sass compilation errors.

It'd be nice to get a new event to catch sass errors, or maybe an option to send sass compilation errors to the stream.

**Comment by robwierzbowski** [comment] 2015-06-09 20:13
Huh, after looking again it looks like I didn't implement this! I really thought I did...

The error logger needs to throw error events on Sass errors as well, gotcha. Some people may want Sass to work like Sass, and see the errors of all files in their browser, others may want Sass to work like gulp and break the build + error event right away. So there should be an option to manage this.

**Comment by robwierzbowski** [comment] 2015-06-09 20:17
Aaaand, here's where I was implementing this:

https://github.com/sindresorhus/gulp-ruby-sass/commit/dadd2f5d73b1577976771370f12590336e1ec0d9

See the note here: https://github.com/sindresorhus/gulp-ruby-sass/blob/dadd2f5d73b1577976771370f12590336e1ec0d9/test.js#L266-L267

Right now we're reading stderr and stdout, but sometimes Sass or gulp give the log in a chunk that includes both normal logging and Sass errors. :trollface: :-1:. Nex3 suggested that we use the ruby bindings, which I have to investigate. I'm not sure how much of this plugin will need to be rewritten in order to make that work. So on the table for now... PR's accepted.

**Comment by robwierzbowski** [comment] 2015-06-09 20:18
Marking this as a duplicate of https://github.com/sindresorhus/gulp-ruby-sass/issues/209, please add new comments there. Thanks for your patience.

**Closed by robwierzbowski** 2015-06-09 20:18 UTC
