### ISSUE TITLE
Sourcemaps don't play well with gulp-rev

### ISSUE THREAD

**Issue by zuzusik** [sindresorhus/gulp-ruby-sass#240] opened 2015-07-30 13:08 UTC
The issue is that instead of having `app-<hash>.css.map` we have `app.css-<hash>.map`

My investigation on this topic:

[Here](https://github.com/sindresorhus/gulp-rev/blob/0e6fb08f46d71c4f9e12c702fb265f4fca90e10c/index.js#L90) `gulp-rev` tries to find reverse file name for processed source map.
But with `gulp-ruby-sass` the map has full file path and sourcemap has only file name.
So the `pathMap` is `{"/usr/home/someuser/projects/app/dist/app.css": "somehash"}` and `reverseFilename`which is taken from sourcemap `file` field is `app.css`.
Then `pathMap[reverseFilename]` is not found and it applies [the general logic](https://github.com/sindresorhus/gulp-rev/blob/0e6fb08f46d71c4f9e12c702fb265f4fca90e10c/index.js#L98) to the sourcemap. And that results in wrong file name.

Keys for `pathMap` are taken from `path` property of the processed file. And this property is set to have full file path in `gulp-ruby-sass` [here](https://github.com/sindresorhus/gulp-ruby-sass/blob/a344f83a615ff9429db0cd07d64d47ba7d6c78fd/index.js#L129). I guess to fix that we need to set file path to have only name instead of full path as this is done in other source map generating libraries. Or maybe we should set file path in sourcemap to be full path (less possible, but I am not sure)

**Comment by robwierzbowski** [comment] 2015-08-09 17:01
Thanks for the detailed summary!

A little background:

Sass reads files off disk, and then prints them back to disk en masse, instead of working file by file in memory like gulp. In order to manage sourcemaps and our Sass temp directory (that receives the Sass output, which is then read into the stream) we rewrite the sourcemap paths as relative paths, so they work with browsers no matter what directory the final files are output in. The final destination path isn't available at the time of Sass sourcemap creation because it's set farther down in the stream by `gulp.dest`.

Would you like to try fixing this and submitting a PR? It seems like you've done a lot of research already.

**Comment by robwierzbowski** [comment] 2015-08-20 15:32
Taking a look at this today.

**Comment by zuzusik** [comment] 2015-08-20 16:21
@robwierzbowski, sorry missed your first message on this topic. I already posted my suggestions on fixing this, but I am not sure if I am on the right way with them. So didn't create the PR.

The main idea is to set only file name instead of full path here: https://github.com/sindresorhus/gulp-ruby-sass/blob/a344f83a615ff9429db0cd07d64d47ba7d6c78fd/index.js#L129
This is how it works with other source maps generating plugins and that is how `gulp-rev` assumes it to be.

**Comment by robwierzbowski** [comment] 2015-08-20 17:10
According to the vinyl file docs (https://github.com/wearefractal/vinyl#file), vinyl files should have an absolute value for `cwd`, `base`, and `path`. So I think we're creating a correct vinyl file.

Can you link to one of the projects that uses only a relative path for `path`?

**Comment by robwierzbowski** [comment] 2015-08-20 17:16
Here, rev is looking for the *sourcemap*'s `file` property:

https://github.com/sindresorhus/gulp-rev/blob/0e6fb08f46d71c4f9e12c702fb265f4fca90e10c/index.js#L81-L83

And as far as I can tell we do give the relative path in the sourcemap file. I'm going to try and reproduce your issue, and debug from there.

**Comment by robwierzbowski** [comment] 2015-08-20 17:28
I'm not reproducing your original error. 

gulp task:

```js

// file sourcemaps
gulp.task('sass', function() {
  return sass('source', { sourcemap: true })
  .on('error', function (err) {
    console.error('Error!', err.message);
  })

  .pipe(rev())

  .pipe(sourcemaps.write('../maps', {
    includeContent: false,
    sourceRoot: 'source'
  }))

  .pipe(gulp.dest('result'));
});
```

Produces:

```
result/fixture-a-10790b6070.css
maps/fixture-a-10790b6070.css.map
```

**Comment by zuzusik** [comment] 2015-08-20 18:00
With latest versions of packages and the code of task you provided, it doesn't even get to this line: https://github.com/sindresorhus/gulp-rev/blob/0e6fb08f46d71c4f9e12c702fb265f4fca90e10c/index.js#L81-L83
because `sourcemaps` array length is `0`.

So, yes, I also can't reproduce the issue now. But still I wonder - if it is safe to omit `sourcemaps.init()` and to rely on `gulp-ruby-sass`?

**Comment by robwierzbowski** [comment] 2015-08-20 18:10
Yep! We basically re-create `sourcemaps.init` here: https://github.com/sindresorhus/gulp-ruby-sass/blob/a344f83a615ff9429db0cd07d64d47ba7d6c78fd/index.js#L131-L146

It's necessary to manage ourselves because nothing can run before our source adapter, and the source adapter is necessary because we need to read the files off of disk. Sass is designed to work off the filesystem on many files at once, so doesn't work well as part of a stream.

**Comment by robwierzbowski** [comment] 2015-08-20 18:11
Closing since sourcemaps seem to be working as expected. If you find any issues with them, please open a ticket. I don't do much with maps in my own work, so appreciate the experience of others that work with them more extensively.

**Closed by robwierzbowski** 2015-08-20 18:11 UTC
